import csv
import os

def generate_items_js_from_csv(csv_path):
    """
    Generate a JavaScript file content with items array and render function.

    The CSV is expected to be tab-delimited with headers: id, author, url.

    Returns:
        String containing the JS code to write to docs/items.js
    """
    items = []

    # Read the CSV file (tab-delimited)
    with open(csv_path, 'r', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile, delimiter='\t')
        rows = sorted(reader, key=lambda x: x['id'])

        for row in rows:
            item_id = row['id'].strip()
            author = row['author'].strip()
            url = row['url'].strip()
            items.append({
                'id': item_id,
                'author': author,
                'url': url,
            })

    # Build JS array string
    lines = ["// Auto-generated by scripts/generate_recipe_html.py", "const items = ["]
    for item in items:
        # Ensure proper escaping for quotes in author
        author = item['author'].replace('"', '\\"')
        url = item['url'].replace('"', '\\"')
        lines.append(
            f'  {{ id: "{item["id"]}", author: "{author}", url: "{url}" }},'
        )
    lines.append("];")

    # Append render helpers and bootstrapping
    lines.extend([
        "",
        "function toTitle(id) {",
        "  return id.split('_').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');",
        "}",
        "",
        "function createRecipeFigure(item) {",
        "  const fig = document.createElement('figure');",
        "  fig.className = 'recipe-item';",
        "  const img = document.createElement('img');",
        "  img.src = `recipe images/${item.id}.png`;",
        "  img.alt = toTitle(item.id);",
        "  const caption = document.createElement('figcaption');",
        "  const h3 = document.createElement('h3');",
        "  h3.textContent = toTitle(item.id);",
        "  const a = document.createElement('a');",
        "  a.href = item.url.startsWith('http') ? item.url : `https://${item.url}`;",
        "  a.target = '_blank';",
        "  a.rel = 'noopener noreferrer';",
        "  a.textContent = item.author;",
        "  caption.appendChild(h3);",
        "  caption.appendChild(a);",
        "  fig.appendChild(img);",
        "  fig.appendChild(caption);",
        "  return fig;",
        "}",
        "",
        "function renderRecipes() {",
        "  const list = document.querySelector('.recipe-list');",
        "  if (!list) return;",
        "  list.innerHTML = '';",
        "  items.forEach(item => list.appendChild(createRecipeFigure(item)));",
        "}",
        "",
        "document.addEventListener('DOMContentLoaded', renderRecipes);",
    ])

    return "\n".join(lines)


def write_items_js(csv_path, js_path):
    js_code = generate_items_js_from_csv(csv_path)
    with open(js_path, 'w', encoding='utf-8') as f:
        f.write(js_code)
    print(f"✓ Generated items JS at {js_path}")
    count_items = js_code.count('id: "')
    print(f"✓ Items count: {count_items}")


if __name__ == "__main__":
    # Get the script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    csv_path = os.path.join(script_dir, "items.csv")
    js_path = os.path.join(script_dir, "..", "docs", "items.js")

    # Generate items.js (no HTML modification)
    write_items_js(csv_path, js_path)
