import csv
import os
import re

def generate_items_array_lines(csv_path):
    """Return list of lines for the items array block."""
    items = []
    with open(csv_path, 'r', encoding='utf-8') as csvfile:
        reader = csv.DictReader(csvfile, delimiter='\t')
        rows = sorted(reader, key=lambda x: x['id'])
        for row in rows:
            items.append({
                'id': row['id'].strip(),
                'author': row['author'].strip(),
                'url': row['url'].strip(),
            })
    lines = ["// Auto-generated by scripts/generate_recipe_html.py", "const items = ["]
    for item in items:
        author = item['author'].replace('"', '\\"')
        url = item['url'].replace('"', '\\"')
        lines.append(f'  {{ id: "{item["id"]}", author: "{author}", url: "{url}" }},')
    lines.append("];")
    return lines


def write_items_js(csv_path, js_path):
    array_lines = generate_items_array_lines(csv_path)
    array_code = "\n".join(array_lines) + "\n"

    if os.path.exists(js_path):
        with open(js_path, 'r', encoding='utf-8') as f:
            original_lines = f.readlines()
        start_idx = None
        for i, line in enumerate(original_lines):
            if re.match(r'^const items = \[', line.strip()):
                start_idx = i
                break
        if start_idx is not None:
            end_idx = None
            for j in range(start_idx, len(original_lines)):
                if original_lines[j].strip() == '];':
                    end_idx = j
                    break
            if end_idx is not None:
                comment_idx = start_idx - 1 if start_idx > 0 and 'Auto-generated' in original_lines[start_idx - 1] else None
                replace_start = comment_idx if comment_idx is not None else start_idx
                new_lines = original_lines[:replace_start] + [l + ('' if l.endswith('\n') else '\n') for l in array_lines] + original_lines[end_idx+1:]
                with open(js_path, 'w', encoding='utf-8') as f:
                    f.writelines(new_lines)
            else:
                with open(js_path, 'w', encoding='utf-8') as f:
                    f.write(array_code + ''.join(original_lines))
        else:
            with open(js_path, 'w', encoding='utf-8') as f:
                f.write(array_code + ''.join(original_lines))
    else:
        with open(js_path, 'w', encoding='utf-8') as f:
            f.write(array_code)

    print(f"✓ Updated items array in {js_path}")
    count_items = array_code.count('id: "')
    print(f"✓ Items count: {count_items}")


if __name__ == "__main__":
    # Get the script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    csv_path = os.path.join(script_dir, "items.csv")
    js_path = os.path.join(script_dir, "..", "docs", "items.js")

    # Generate items.js (no HTML modification)
    write_items_js(csv_path, js_path)
